#!/bin/sh
#set -x
#Fix user home directory permissions 
#  if needed and exec docker-run script

RUN_USER="ffsync"
USER_DIR=`eval echo "~$RUN_USER"`

[ -d "$USER_DIR" ] || mkdir -p "$USER_DIR"

DIR_OWNER=`stat -c '%U' "$USER_DIR"`

if [ "$DIR_OWNER" != "$RUN_USER" ]; then
	chown -R "$RUN_USER:$RUN_USER" "$USER_DIR"
fi

su-exec $RUN_USER /bin/docker-run
